packages:
  - packages/*
  - apps/*

catalog:
  '@sqlite.org/sqlite-wasm': ^3.51.2-build5

ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - sharp
  - workerd
