packages:
  - packages/*
  - apps/*

catalog:
  '@sqlite.org/sqlite-wasm': 3.53.0-build1
  kysely: ^0.28.10
  react: ^19.2.7
  react-dom: ^19.2.7
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3

ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - react-grab
  - sharp
  - workerd
