/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface D1Migrations {
  applied_at: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface List {
  createdAt: string;
  id: string;
  name: string;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  updatedAt: string;
  userId: string;
}

export interface User {
  createdAt: string;
  email: string;
  id: string;
  name: string;
  updatedAt: string;
}

export interface UserToList {
  listId: string;
  userId: string;
}

export interface Verification {
  createdAt: string;
  expiresAt: string;
  target: string;
  value: string;
}

export interface DB {
  d1_migrations: D1Migrations;
  list: List;
  session: Session;
  user: User;
  user_to_list: UserToList;
  verification: Verification;
}
