/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthMagicLinkVerifyRouteImport } from './routes/_auth/magic-link-verify'
import { Route as AppListIdRouteRouteImport } from './routes/_app/list.$id/route'
import { Route as AppListIdIndexRouteImport } from './routes/_app/list.$id/index'
import { Route as AppListIdTrendingRouteImport } from './routes/_app/list.$id/trending'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkVerifyRoute = AuthMagicLinkVerifyRouteImport.update({
  id: '/magic-link-verify',
  path: '/magic-link-verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppListIdRouteRoute = AppListIdRouteRouteImport.update({
  id: '/list/$id',
  path: '/list/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListIdIndexRoute = AppListIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppListIdRouteRoute,
} as any)
const AppListIdTrendingRoute = AppListIdTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AppListIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/sign-in': typeof AuthSignInRoute
  '/list/$id': typeof AppListIdRouteRouteWithChildren
  '/list/$id/trending': typeof AppListIdTrendingRoute
  '/list/$id/': typeof AppListIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/sign-in': typeof AuthSignInRoute
  '/list/$id/trending': typeof AppListIdTrendingRoute
  '/list/$id': typeof AppListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/list/$id': typeof AppListIdRouteRouteWithChildren
  '/_app/list/$id/trending': typeof AppListIdTrendingRoute
  '/_app/list/$id/': typeof AppListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/magic-link-verify'
    | '/sign-in'
    | '/list/$id'
    | '/list/$id/trending'
    | '/list/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/magic-link-verify'
    | '/sign-in'
    | '/list/$id/trending'
    | '/list/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/magic-link-verify'
    | '/_auth/sign-in'
    | '/_app/'
    | '/_app/list/$id'
    | '/_app/list/$id/trending'
    | '/_app/list/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/magic-link-verify': {
      id: '/_auth/magic-link-verify'
      path: '/magic-link-verify'
      fullPath: '/magic-link-verify'
      preLoaderRoute: typeof AuthMagicLinkVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/list/$id': {
      id: '/_app/list/$id'
      path: '/list/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof AppListIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/list/$id/': {
      id: '/_app/list/$id/'
      path: '/'
      fullPath: '/list/$id/'
      preLoaderRoute: typeof AppListIdIndexRouteImport
      parentRoute: typeof AppListIdRouteRoute
    }
    '/_app/list/$id/trending': {
      id: '/_app/list/$id/trending'
      path: '/trending'
      fullPath: '/list/$id/trending'
      preLoaderRoute: typeof AppListIdTrendingRouteImport
      parentRoute: typeof AppListIdRouteRoute
    }
  }
}

interface AppListIdRouteRouteChildren {
  AppListIdTrendingRoute: typeof AppListIdTrendingRoute
  AppListIdIndexRoute: typeof AppListIdIndexRoute
}

const AppListIdRouteRouteChildren: AppListIdRouteRouteChildren = {
  AppListIdTrendingRoute: AppListIdTrendingRoute,
  AppListIdIndexRoute: AppListIdIndexRoute,
}

const AppListIdRouteRouteWithChildren = AppListIdRouteRoute._addFileChildren(
  AppListIdRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppListIdRouteRoute: typeof AppListIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppListIdRouteRoute: AppListIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthMagicLinkVerifyRoute: typeof AuthMagicLinkVerifyRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMagicLinkVerifyRoute: AuthMagicLinkVerifyRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
