/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthMagicLinkVerifyRouteImport } from './routes/_auth/magic-link-verify'
import { Route as AppListIdRouteImport } from './routes/_app/list.$id'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback.google'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkVerifyRoute = AuthMagicLinkVerifyRouteImport.update({
  id: '/magic-link-verify',
  path: '/magic-link-verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppListIdRoute = AppListIdRouteImport.update({
  id: '/list/$id',
  path: '/list/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/sign-in': typeof AuthSignInRoute
  '/': typeof AppIndexRoute
  '/list/$id': typeof AppListIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/sign-in': typeof AuthSignInRoute
  '/': typeof AppIndexRoute
  '/list/$id': typeof AppListIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/magic-link-verify': typeof AuthMagicLinkVerifyRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/list/$id': typeof AppListIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/magic-link-verify'
    | '/sign-in'
    | '/'
    | '/list/$id'
    | '/api/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/magic-link-verify'
    | '/sign-in'
    | '/'
    | '/list/$id'
    | '/api/auth/callback/google'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/magic-link-verify'
    | '/_auth/sign-in'
    | '/_app/'
    | '/_app/list/$id'
    | '/api/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/magic-link-verify': {
      id: '/_auth/magic-link-verify'
      path: '/magic-link-verify'
      fullPath: '/magic-link-verify'
      preLoaderRoute: typeof AuthMagicLinkVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/list/$id': {
      id: '/_app/list/$id'
      path: '/list/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof AppListIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppListIdRoute: typeof AppListIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppListIdRoute: AppListIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthMagicLinkVerifyRoute: typeof AuthMagicLinkVerifyRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMagicLinkVerifyRoute: AuthMagicLinkVerifyRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
